# promptfooconfig.yaml
prompts:
  - prompt.json
providers:
  - id: openai:gpt-4o
    config:
      temperature: 0
      response_format:
        type: json_schema
        json_schema:
          name: test
          schema:
            type: object
            properties:
              response:
                type: string
            required:
              - response
tests: tests.yaml
